### ISSUE TITLE
Any aritical relate to this repo ?

### ISSUE THREAD

**Issue by urmyfaith** [TannerJin/Swift-MemoryLayout#1]
Any aritical relate to this repo  to get more detail ?

In this repo, some notes and graph is not fully precisely decribled  the memoryLayout .

**Comment by TannerJin** [comment]
Here are my reference links
[swift](https://github.com/apple/swift)
[Exploring Swift Memory Layout](https://academy.realm.io/posts/goto-mike-ash-exploring-swift-memory-layout/)
[Exploring Swift Memory Layout](https://www.youtube.com/watch?v=ERYNyrfXjlg&t=498s)

国人: [这是我之前研究的过程，仅供参考，有些没更新，最好以当前项目为准](https://tannerjin.github.io/2018/12/27/Swift%E5%86%85%E5%AD%98%E5%B8%83%E5%B1%80/)

**Comment by urmyfaith** [comment]
Get,3ks.
